# docker compose -f 'docker-compose/postgres.yml' up -d --build

services:
  postgres:
    image: postgres:17
    container_name: postgres-17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=pt-br.UTF-8"

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data: