# docker compose -f 'docker-compose/postgres.yml' up -d --build

services:
  postgres:
    image: ${POSTGRES_IMAGE:-postgres:17}
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres-17}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "${POSTGRES_INITDB_ARGS:---encoding=UTF8 --locale=pt-br.UTF-8}"

    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: